### PR TITLE
Upgrade to 0.19

### PR DESCRIPTION
**Pull request by BendingBender**
Hi,

I've just ported your lib to Elm 0.19, it would be great if you could merge the changes and make a new release.

I had to remove the custom operators but I've introduced `composep` to simulate the custom operators with pipes.

In the meantime, I'll release this lib as `BendingBender/elm-fields`. Thank you for this great lib!

### CODE REVIEW

**Comment by sjorn3** [comment]
Fantastic work @BendingBender!

I'll just leave this link to document why the operators had to go: https://gist.github.com/evancz/769bba8abb9ddc3bf81d69fa80cc76b1, but I think your solution is good.

I'll take a closer look at the code and merge if all's well sometime this evening.

**Comment by BendingBender** [comment]
I've just noticed that I forgot to fix unit tests, fixing them right now.

**Comment by BendingBender** [comment]
Not sure how to fix the `.travis.yml`. I've found a simple config in `https://github.com/avh4/elm-fifo`, but they're using a local `elm-test` install via node. If it doesn't disturb you to have node as build dependency, then this could be something that you could easily set up in your project.

**Comment by BendingBender** [comment]
Found a solution for running tests here: https://elmlang.slack.com/archives/C13L7S5GR/p1535147099000100:

1. The `LICENCE` file must be named exactly that. Not `LICENSE.txt`.

2. `String.toInt("0x123")` gets an error rather than interpreting `"123"` as a hex string. Use `rtfeldman/elm-hex` instead.

3. elm-test is much easier to use, but you have to upgrade:

    `npm install -g elm-test@0.19.0-beta4`

  You no longer need `elm.json` in the `tests` directory, just your test files. The test files themselves don’t change, except as necessary to make them work in 0.19.

  You need to put in elm.json:

  `"test-dependencies": {`
      `"elm-explorations/test": "1.0.0 <= v < 2.0.0"`
  `}`

Plus any other test-only dependencies.

4. `travis.yml` changes for automated testing:

  The travis cache no longer does you any good, since the `build-artifacts` directory is now stored in `~/.elm`. Also, the 0.19 compiler is so fast that it hardly matters.

It appears that the 1-cpu optimization for `elm make` is no longer necessary.

Remember to bump the versions for `elm` (0.19) and `elm-make` (0.19.0-beta4) in the `npm install` lines

**Comment by sjorn3** [comment]
Are these changes all implemented? Is there something that you need me to change on Travis?

Unfortunately I disabled Pull Request builds previously, I've re-enabled them now though perhaps they won't work immediately. If there are no changes between now and merging I'll push a dummy commit to trigger the build and then remove it.

**Comment by BendingBender** [comment]
Should all be done by now. But I haven't tested the travis build. Locally, all tests pass.

**Comment by BendingBender** [comment]
Beware: this could happen to you when you try to publish because of the incorrect license field value you had in your old `elm-package.json`: https://elmlang.slack.com/archives/C13L7S5GR/p1535466787000100

The only known workaround atm seems to be to rename the package. But of course you should try it out first.

**Comment by sjorn3** [comment]
Alrighty, Travis ran smoothly and all tests passed on a dummy branch, so I think things are looking good for merge. Hopefully publishing isn't too painful.

Thanks again!

**Comment by BendingBender** [comment]
Great! Thank you!

**Pull request merged**
